import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const here = dirname(fileURLToPath(import.meta.url))
const frontend = resolve(here, '..')
const root = resolve(frontend, '..')
const readFrontend = (path) => readFileSync(resolve(frontend, path), 'utf8')
const readRoot = (path) => readFileSync(resolve(root, path), 'utf8')

test('l’administration centralise les trois ateliers éditoriaux', () => {
  const app = readFrontend('src/App.jsx')
  const layout = readFrontend('src/components/layout/AdminLayout.jsx')
  const atelier = readFrontend('src/pages/admin/AtelierEditorial.jsx')
  const catalogue = readFrontend('src/pages/admin/ChapitreEdit.jsx')

  assert.match(app, /path="contenus" element=\{<AtelierEditorial/)
  assert.match(app, /path="resumes\/:chapitreId"/)
  assert.match(app, /path="exercices-guides\/:chapitreId"/)
  assert.match(app, /path="devoirs\/:devoirId"/)
  assert.match(layout, /Atelier/)
  assert.match(layout, /Résumés/)
  assert.match(layout, /Devoirs/)
  assert.match(atelier, /Brouillons privés/)
  assert.match(atelier, /Historique conservé/)
  assert.match(catalogue, /admin\/resumes\/\$\{c\.id\}/)
  assert.match(catalogue, /Ouvrir les devoirs/)
  assert.doesNotMatch(catalogue, /supprimerDevoir/)
})

test('les résumés ont brouillon privé, historique, LaTeX et suivi des commentaires', () => {
  const migration = readRoot('supabase/migrations/2026071409_resumes_editorial.sql')
  const editor = readFrontend('src/pages/admin/ResumesAdmin.jsx')
  const student = readFrontend('src/pages/ResumeLecon.jsx')

  assert.match(migration, /^begin;/m)
  assert.match(migration, /^commit;/m)
  assert.match(migration, /create table if not exists public\.resume_brouillons/)
  assert.match(migration, /create table if not exists public\.resume_versions/)
  assert.match(migration, /create table if not exists public\.lecon_commentaire_suivi/)
  assert.match(migration, /where c\.resume_published = false[\s\S]*on conflict \(chapitre_id\) do nothing/)
  assert.match(migration, /resume_revision_conflit/)
  assert.match(migration, /brouillon_revision_conflit/)
  assert.match(migration, /set search_path = pg_catalog, public/)
  assert.match(editor, /get_resume_admin/)
  assert.match(editor, /sauvegarder_brouillon_resume_admin/)
  assert.match(editor, /publier_resume_admin/)
  assert.match(editor, /changer_statut_commentaire_resume_admin/)
  assert.match(editor, /Enregistrer le brouillon/)
  assert.match(editor, /Publier cette version/)
  assert.match(editor, /MathMarkdown/)
  assert.match(editor, /beforeunload/)
  assert.match(student, /MathMarkdown/)
  assert.doesNotMatch(student, /ReactMarkdown/)
})

test('les devoirs sont modifiés par version sans effacer les anciennes copies', () => {
  const migration = readRoot('supabase/migrations/2026071410_devoirs_versionnes.sql')
  const editor = readFrontend('src/pages/admin/DevoirsAdmin.jsx')
  const resultat = readFrontend('src/pages/Resultat.jsx')

  assert.match(migration, /^begin;/m)
  assert.match(migration, /^commit;/m)
  assert.match(migration, /create table if not exists public\.devoirs_editoriaux/)
  assert.match(migration, /version_devoir/)
  assert.match(migration, /version_devoir_immuable/)
  assert.match(migration, /preparer_brouillon_devoir_admin_v1/)
  assert.match(migration, /enregistrer_brouillon_devoir_admin_v1/)
  assert.match(migration, /publier_devoir_admin_v1/)
  assert.match(migration, /publication_id/)
  assert.match(migration, /contenu_non_autorise/)
  assert.match(migration, /current_quiz_id/)
  assert.match(migration, /set search_path = pg_catalog, public/)
  assert.match(editor, /Publiés/)
  assert.match(editor, /Brouillons/)
  assert.match(editor, /Archivés/)
  assert.match(editor, /Modifier dans un brouillon/)
  assert.match(editor, /Enregistrer le brouillon/)
  assert.match(editor, /MathMarkdown/)
  assert.match(editor, /useParams/)
  assert.match(editor, /beforeunload/)
  assert.match(resultat, /replayQuizId/)
  assert.match(resultat, /Aucune version disponible/)
})

test('le schéma canonique inclut les migrations éditoriales', () => {
  const schema = readRoot('supabase/schema.sql')
  assert.match(schema, /public\.publier_exercices_admin_v3/)
  assert.match(schema, /public\.get_resume_admin/)
  assert.match(schema, /public\.publier_resume_admin/)
  assert.match(schema, /public\.devoirs_editoriaux/)
  assert.match(schema, /public\.publier_devoir_admin_v1/)
  assert.doesNotMatch(schema, /^\+/m)
})
