-- Récompenses des sept parcours SVT de Terminale A.
-- La clé (path_id, lesson_id) rend la migration rejouable sans dupliquer les données.

insert into public.lesson_rewards (path_id, lesson_id, xp_awarded)
values
  ('terminale-svt-l1-emotional-reactions', 'terminale-svt-l1-emotional-reactions-overview', 40),
  ('terminale-svt-l1-emotional-reactions', 'terminale-svt-l1-emotional-reactions-manifestations', 55),
  ('terminale-svt-l1-emotional-reactions', 'terminale-svt-l1-emotional-reactions-causes-stressors', 60),
  ('terminale-svt-l1-emotional-reactions', 'terminale-svt-l1-emotional-reactions-nervous-regulation', 65),
  ('terminale-svt-l1-emotional-reactions', 'terminale-svt-l1-emotional-reactions-hormonal-regulation', 70),
  ('terminale-svt-l1-emotional-reactions', 'terminale-svt-l1-emotional-reactions-mission-finale', 80),
  ('terminale-svt-l2-brain-activity', 'terminale-svt-l2-brain-activity-overview', 40),
  ('terminale-svt-l2-brain-activity', 'terminale-svt-l2-brain-activity-cerebral-areas', 55),
  ('terminale-svt-l2-brain-activity', 'terminale-svt-l2-brain-activity-movement-preparation', 60),
  ('terminale-svt-l2-brain-activity', 'terminale-svt-l2-brain-activity-movement-execution', 65),
  ('terminale-svt-l2-brain-activity', 'terminale-svt-l2-brain-activity-memory', 70),
  ('terminale-svt-l2-brain-activity', 'terminale-svt-l2-brain-activity-mission-finale', 80),
  ('terminale-svt-l3-origin-of-life', 'terminale-svt-l3-origin-of-life-overview', 40),
  ('terminale-svt-l3-origin-of-life', 'terminale-svt-l3-origin-of-life-early-earth-evidence', 55),
  ('terminale-svt-l3-origin-of-life', 'terminale-svt-l3-origin-of-life-photosynthesis-oxygenation', 60),
  ('terminale-svt-l3-origin-of-life', 'terminale-svt-l3-origin-of-life-extreme-environments', 65),
  ('terminale-svt-l3-origin-of-life', 'terminale-svt-l3-origin-of-life-experimental-origin', 70),
  ('terminale-svt-l3-origin-of-life', 'terminale-svt-l3-origin-of-life-mission-finale', 80),
  ('terminale-svt-l4-human-lineage', 'terminale-svt-l4-human-lineage-overview', 40),
  ('terminale-svt-l4-human-lineage', 'terminale-svt-l4-human-lineage-cranial-transformations', 55),
  ('terminale-svt-l4-human-lineage', 'terminale-svt-l4-human-lineage-bipedal-stature', 60),
  ('terminale-svt-l4-human-lineage', 'terminale-svt-l4-human-lineage-molecular-parentage', 65),
  ('terminale-svt-l4-human-lineage', 'terminale-svt-l4-human-lineage-evolution-theories', 70),
  ('terminale-svt-l4-human-lineage', 'terminale-svt-l4-human-lineage-mission-finale', 80),
  ('terminale-svt-l5-sex-blood-heredity', 'terminale-svt-l5-sex-blood-heredity-overview', 40),
  ('terminale-svt-l5-sex-blood-heredity', 'terminale-svt-l5-sex-blood-heredity-abo-alleles', 55),
  ('terminale-svt-l5-sex-blood-heredity', 'terminale-svt-l5-sex-blood-heredity-abo-crosses', 60),
  ('terminale-svt-l5-sex-blood-heredity', 'terminale-svt-l5-sex-blood-heredity-sex-chromosomes', 65),
  ('terminale-svt-l5-sex-blood-heredity', 'terminale-svt-l5-sex-blood-heredity-sex-cross', 70),
  ('terminale-svt-l5-sex-blood-heredity', 'terminale-svt-l5-sex-blood-heredity-mission-finale', 80),
  ('terminale-svt-l6-genetic-predictions', 'terminale-svt-l6-genetic-predictions-overview', 40),
  ('terminale-svt-l6-genetic-predictions', 'terminale-svt-l6-genetic-predictions-pedigree-method', 55),
  ('terminale-svt-l6-genetic-predictions', 'terminale-svt-l6-genetic-predictions-sickle-cell', 60),
  ('terminale-svt-l6-genetic-predictions', 'terminale-svt-l6-genetic-predictions-hemophilia-x-linked', 65),
  ('terminale-svt-l6-genetic-predictions', 'terminale-svt-l6-genetic-predictions-screening-counseling', 70),
  ('terminale-svt-l6-genetic-predictions', 'terminale-svt-l6-genetic-predictions-mission-finale', 80),
  ('terminale-svt-l7-protein-biosynthesis', 'terminale-svt-l7-protein-biosynthesis-overview', 40),
  ('terminale-svt-l7-protein-biosynthesis', 'terminale-svt-l7-protein-biosynthesis-molecular-actors', 55),
  ('terminale-svt-l7-protein-biosynthesis', 'terminale-svt-l7-protein-biosynthesis-genetic-code', 60),
  ('terminale-svt-l7-protein-biosynthesis', 'terminale-svt-l7-protein-biosynthesis-transcription', 65),
  ('terminale-svt-l7-protein-biosynthesis', 'terminale-svt-l7-protein-biosynthesis-translation', 70),
  ('terminale-svt-l7-protein-biosynthesis', 'terminale-svt-l7-protein-biosynthesis-mission-finale', 80)
on conflict (path_id, lesson_id)
do update set xp_awarded = excluded.xp_awarded;
